version: "3.8"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
      - seq-data:/data          
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:80
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    expose:
      - 1883
      - 8883
      - 9001
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
volumes:
  portainer-data:
  seq-data: